### ISSUE TITLE
cannot get nodes in ES transport when using ES6.4.3 on server 

### ISSUE THREAD

**Issue by simonmiller99** [tarasrng/olastic-demo#1]
hi - this project is exactly what I was looking for to make the ES indices I have available to PowerBI. My ES server is running 6.4.3 but olastic is running an earlier version 5.4.0. Whatever values I supply for host, port, cluster I get the same answer from olastic "no nodes available"   StackOverflow suggests that ES version compatibility  is a major cause of this error. Stepping the ESConfigIMpl code I can see that "nodes" never gets populated, so the exception is technically correct. 

Do you have any plans to update the olastic project and demo ?  I have written JEST code that gets an answer from the ES cluster so I do not believe the cluster to be at fault.

**Comment by tarasrng** [comment]
Hi. 
Olastic doesn't support ES 6.x, that's why you have this issue. 
We are going to upgrade Olastic to support ES 6.x, but it requires some efforts because there was one breaking change - they removed support of _type field. That's why I think upgrade won't be done in the nearest future. Anyway, pull requests are welcome.
